name: Deploy Vanilla JavaScript To-Do-App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      APP_NAME: 'PWA Checklist App'  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Environment Variable
        run: echo "App Name: $APP_NAME"

      - name: Install Dependencies (if any)
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      - name: Build Project (if any build step exists)
        run: |
          if [ -f package.json ]; then
            npm run build
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
